-- MSSQL

WITH CTE AS (
    SELECT H.HACKER_ID, H.NAME, COUNT(C.CHALLENGE_ID) AS TOTAL, COUNT(*) OVER (PARTITION BY COUNT(C.CHALLENGE_ID)) AS N
FROM HACKERS H JOIN CHALLENGES C ON H.HACKER_ID = C.HACKER_ID
GROUP BY H.HACKER_ID, H.NAME)

SELECT HACKER_ID, NAME, TOTAL FROM CTE
WHERE NOT (N>1 and TOTAL< (SELECT MAX(TOTAL)FROM CTE))
ORDER BY TOTAL DESC, HACKER_ID 
