-- MSSQL

WITH CTE AS (SELECT H.HACKER_ID, H.NAME, MAX(S.SCORE) AS MSCORE 
FROM HACKERS H JOIN SUBMISSIONS S ON H.HACKER_ID = S.HACKER_ID
GROUP BY H.HACKER_ID, H.NAME, S.CHALLENGE_ID)

SELECT HACKER_ID, NAME, SUM(MSCORE) FROM CTE
GROUP BY HACKER_ID, NAME
HAVING SUM(MSCORE)>0
ORDER BY SUM(MSCORE) DESC, HACKER_ID
