-- MySQL

SELECT CONCAT(NAME,'(',LEFT(OCCUPATION,1),')') AS conc FROM OCCUPATIONS
ORDER BY conc;

SELECT CONCAT('There are a total of ',COUNT(OCCUPATION),' ',LOWER(OCCUPATION),'s.')
FROM OCCUPATIONS
GROUP BY OCCUPATION
ORDER BY COUNT(OCCUPATION),OCCUPATION;
