--MSSQL

WITH TEMP AS
(SELECT LAT_N, ROW_NUMBER() OVER (ORDER BY LAT_N) AS R FROM STATION)

SELECT CAST(AVG(LAT_N) AS DECIMAL(6,4)) FROM TEMP
WHERE R-1 IN (CEILING((SELECT MAX(R)-1 FROM TEMP)/2), FLOOR((SELECT MAX(R)-1 FROM TEMP)/2))



